[project]
name = "template-rf-detr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clearml[s3]>=2.0.2",
    "pydantic-settings>=2.12.0",
    "rfdetr>=1.3.0",
    "rich>=14.2.0",
    "supervision>=0.26.1",
]
